import { SettingsCard, SettingsSummary } from '@/types/settings';

export const MOCK_SETTINGS_SUMMARY: SettingsSummary = {
  environment: "production",
  lastUpdatedAt: "2025-05-24T14:32:00Z",
  lastUpdatedBy: "Gabriel Silva",
  security: {
    status: "protected",
    twoFactorEnabled: true,
    activeSessionsCount: 3,
    lastSecurityAudit: "2025-05-20T09:00:00Z",
  },
  integrations: {
    gatewaysCount: 8,
    webhooksCount: 24,
    apiKeysCount: 12,
    activeEnvironments: 3,
  },
  apiUsage: {
    callsThisMonth: 1234567,
    limit: 1600000,
    percentUsed: 77.2,
  },
  company: {
    name: "Basileia Corp",
    id: "5312",
    plan: "Enterprise",
    region: "São Paulo, BR",
  },
};

export const MOCK_SETTINGS_CARDS: SettingsCard[] = [
  {
    id: "company",
    title: "Perfil da empresa",
    description: "Dados da empresa, documentos, contatos e informações fiscais.",
    icon: "Building2",
    iconBg: "bg-blue-50 text-blue-600 border-blue-100",
    category: "Empresa",
    categoryColor: "blue",
    badge: null,
    route: "/dashboard/settings/company",
    permission: ["owner", "admin", "financial"],
  },
  {
    id: "branding",
    title: "Identidade visual",
    description: "Logotipo, cores, tipografia e personalização da marca.",
    icon: "Palette",
    iconBg: "bg-pink-50 text-pink-600 border-pink-100",
    category: "Empresa",
    categoryColor: "blue",
    badge: null,
    route: "/dashboard/settings/branding",
    permission: ["owner", "admin"],
  },
  {
    id: "theme",
    title: "Tema",
    description: "Escolha entre tema claro, escuro ou automático.",
    icon: "Moon",
    iconBg: "bg-amber-50 text-amber-600 border-amber-100",
    category: "Sistema",
    categoryColor: "slate",
    badge: null,
    route: "/dashboard/settings/theme",
    permission: ["owner", "admin", "financial", "developer", "support", "auditor"],
  },
  {
    id: "security",
    title: "Acesso e segurança",
    description: "Políticas de senha, sessões, bloqueios e proteção da conta.",
    icon: "ShieldCheck",
    iconBg: "bg-emerald-50 text-emerald-600 border-emerald-100",
    category: "Segurança",
    categoryColor: "red",
    badge: null,
    route: "/dashboard/settings/security",
    permission: ["owner", "admin"],
  },
  {
    id: "two-factor",
    title: "Autenticação 2FA",
    description: "Configure autenticação em duas etapas para sua conta.",
    icon: "KeyRound",
    iconBg: "bg-indigo-50 text-indigo-650 border-indigo-100",
    category: "Segurança",
    categoryColor: "red",
    badge: { type: "status", label: "Ativo", color: "green" },
    route: "/dashboard/settings/two-factor",
    permission: ["owner", "admin", "financial", "developer", "support", "auditor"],
  },
  {
    id: "api-keys",
    title: "API Keys",
    description: "Crie e gerencie chaves de API para integrações.",
    icon: "Key",
    iconBg: "bg-yellow-50 text-yellow-600 border-yellow-100",
    category: "Integrações",
    categoryColor: "violet",
    badge: { type: "count", value: 12, color: "violet" },
    route: "/dashboard/settings/api-keys",
    permission: ["owner", "admin", "developer"],
  },
  {
    id: "gateways",
    title: "Gateways",
    description: "Conecte e gerencie seus provedores de pagamento.",
    icon: "Landmark",
    iconBg: "bg-purple-50 text-purple-650 border-purple-100",
    category: "Integrações",
    categoryColor: "violet",
    badge: { type: "count", value: 8, color: "violet" },
    route: "/dashboard/gateways",
    permission: ["owner", "admin", "financial"],
    isExternal: true,
  },
  {
    id: "webhooks",
    title: "Webhooks",
    description: "Configure eventos e URLs para integrações em tempo real.",
    icon: "Webhook",
    iconBg: "bg-orange-50 text-orange-600 border-orange-100",
    category: "Integrações",
    categoryColor: "violet",
    badge: { type: "count", value: 24, color: "violet" },
    route: "/dashboard/webhooks",
    permission: ["owner", "admin", "developer"],
    isExternal: true,
  },
  {
    id: "ai",
    title: "IA",
    description: "Recursos de inteligência artificial e automações inteligentes.",
    icon: "Sparkles",
    iconBg: "bg-violet-50 text-violet-600 border-violet-100",
    category: "Operação",
    categoryColor: "green",
    badge: { type: "status", label: "Ativo", color: "green" },
    route: "/dashboard/settings/ai",
    permission: ["owner", "admin"],
  },
  {
    id: "fx",
    title: "FX / Multi-moeda",
    description: "Gerencie moedas, taxas de câmbio e regras de conversão.",
    icon: "DollarSign",
    iconBg: "bg-teal-50 text-teal-650 border-teal-100",
    category: "Operação",
    categoryColor: "green",
    badge: { type: "count", value: 6, color: "green" },
    route: "/dashboard/settings/fx",
    permission: ["owner", "admin", "financial"],
  },
  {
    id: "notifications",
    title: "Notificações",
    description: "E-mails, SMS, WhatsApp e alertas do sistema.",
    icon: "Bell",
    iconBg: "bg-amber-50 text-amber-600 border-amber-100",
    category: "Operação",
    categoryColor: "green",
    badge: null,
    route: "/dashboard/settings/notifications",
    permission: ["owner", "admin", "financial", "developer", "support", "auditor"],
  },
  {
    id: "environments",
    title: "Ambientes",
    description: "Gerencie ambientes: produção, homologação e desenvolvimento.",
    icon: "Layers",
    iconBg: "bg-cyan-50 text-cyan-650 border-cyan-100",
    category: "Sistema",
    categoryColor: "slate",
    badge: { type: "count", value: 3, color: "blue" },
    route: "/dashboard/settings/environments",
    permission: ["owner", "admin", "developer"],
  },
  {
    id: "permissions",
    title: "Permissões",
    description: "Papéis, permissões e controle de acesso por usuário e equipe.",
    icon: "Users",
    iconBg: "bg-indigo-50 text-indigo-600 border-indigo-100",
    category: "Segurança",
    categoryColor: "red",
    badge: { type: "count", value: 18, color: "red" },
    route: "/dashboard/settings/permissions",
    permission: ["owner", "admin"],
  },
  {
    id: "audit",
    title: "Auditoria",
    description: "Logs de atividades, alterações e eventos críticos do sistema.",
    icon: "ClipboardList",
    iconBg: "bg-slate-50 text-slate-500 border-slate-200",
    category: "Sistema",
    categoryColor: "slate",
    badge: { type: "count", value: 1532, color: "blue" },
    route: "/dashboard/audit",
    permission: ["owner", "admin", "auditor"],
    isExternal: true,
  },
  {
    id: "advanced",
    title: "Avançado",
    description: "Configurações técnicas, limites, recursos experimentais e mais.",
    icon: "SlidersHorizontal",
    iconBg: "bg-zinc-100 text-zinc-700 border-zinc-200",
    category: "Sistema",
    categoryColor: "slate",
    badge: null,
    route: "/dashboard/settings/advanced",
    permission: ["owner"],
  },
];
