import { CheckoutSchema } from './types';

export const mockSchema: CheckoutSchema = {
  schema_version: '1.0',
  checkout_id: 'chk_mock',
  version_id: 'ver_mock',
  name: 'Checkout Premium Internacional',
  status: 'published',
  brand_tokens: {
    logo: null, // Pode ser uma URL
    primary_color: '#6D28D9', // Roxo
    secondary_color: '#A78BFA',
    background_color: '#F8F5FF',
    font_family: 'Inter',
    font_scale: 'moderna',
    button_radius: 8,
    card_radius: 12,
    input_radius: 8,
    shadow_style: 'soft',
  },
  settings: {
    layout: 'two_columns',
    currency: 'BRL',
    language: 'pt-BR',
    show_secure_header: true,
    enable_coupon: true,
    enable_whatsapp_support: true,
    success_redirect_url: null,
    failure_redirect_url: null,
    pixel_facebook: null,
    pixel_gtm: null,
    custom_domain: null,
  },
  payment_config: {
    methods: ['pix', 'credit_card', 'boleto'],
    pix: { enabled: true, discount_percent: 5, expiration_minutes: 30, custom_message: 'Aprovação imediata' },
    credit_card: { enabled: true, max_installments: 12, interest_rate_percent: 1.99, antifraud: true, capture: 'automatic' },
    boleto: { enabled: true, due_days: 3, instructions: 'Não aceitar após o vencimento', fine_percent: 2, interest_daily_percent: 0.033 },
    gateway_id: null,
  },
  blocks: [
    {
      id: 'secure_header_01',
      type: 'secure_header',
      name: 'Cabeçalho Seguro',
      order: 0,
      locked: true,
      visible: true,
      required: true,
      content: {
        text: 'Ambiente 100% seguro',
      },
    },
    {
      id: 'hero_01',
      type: 'hero',
      name: 'Hero Principal',
      order: 1,
      locked: false,
      visible: true,
      required: false,
      content: {
        title: 'Checkout Premium Internacional',
        subtitle: 'A solução completa para escalar seu negócio digital.',
        badge: 'Mais vendido',
        badge_color: '#F59E0B',
        rating: 4.9,
        rating_count: 2431,
        image: null,
        benefits: ['Acesso imediato', 'Atualizações vitalícias', 'Suporte dedicado 24/7'],
      },
      style: {
        background: 'gradient-purple',
        background_gradient_start: '#4C1D95',
        background_gradient_end: '#7C3AED',
        padding_top: 32,
        padding_bottom: 32,
        border_radius: 16,
        text_color: '#FFFFFF',
        image_position: 'right',
      },
      responsive: {
        desktop: { visible: true, order: 1, style: {} },
        tablet: { visible: true, order: 1, style: {} },
        mobile: { visible: true, order: 1, style: { image_position: 'top', text_align: 'center', title_short: 'Finalize com segurança' } },
      },
    },
    {
      id: 'customer_fields_01',
      type: 'customer_fields',
      name: 'Dados do Cliente',
      order: 2,
      locked: true,
      visible: true,
      required: true,
      content: {
        fields: [
          { name: 'full_name', label: 'Nome completo', required: true, visible_for: ['all'] },
          { name: 'email', label: 'E-mail', required: true, visible_for: ['all'] },
          { name: 'document', label: 'CPF', required: true, visible_for: ['all'] },
          { name: 'phone', label: 'WhatsApp', required: false, visible_for: ['all'] },
        ],
      },
    },
    {
      id: 'payment_methods_01',
      type: 'payment_methods',
      name: 'Métodos de Pagamento',
      order: 3,
      locked: true,
      visible: true,
      required: true,
      content: {
        title: 'Escolha a forma de pagamento',
        default_method: 'pix',
      },
    },
    {
      id: 'coupon_01',
      type: 'coupon',
      name: 'Cupom de Desconto',
      order: 4,
      locked: false,
      visible: true,
      required: false,
      content: {
        placeholder: 'Tem um cupom?',
      },
    },
    {
      id: 'order_summary_01',
      type: 'order_summary',
      name: 'Resumo do Pedido',
      order: 5,
      locked: true,
      visible: true,
      required: true,
      content: {
        title: 'Resumo da Compra',
        items: [
          { name: 'Acesso Premium', price: 497.00 },
        ],
      },
    },
    {
      id: 'cta_01',
      type: 'cta',
      name: 'Botão Finalizar',
      order: 6,
      locked: true,
      visible: true,
      required: true,
      content: {
        text: 'Finalizar Compra',
        subtext: 'Compra 100% segura',
      },
    },
    {
      id: 'guarantee_01',
      type: 'guarantee',
      name: 'Selo de Garantia',
      order: 7,
      locked: false,
      visible: true,
      required: false,
      content: {
        days: 7,
        title: 'Garantia Incondicional',
        description: 'Se não gostar, devolvemos 100% do seu dinheiro.',
      },
    },
  ],
  conditions: [],
  tracking: {
    facebook_pixel: null,
    google_tag_manager: null,
    custom_scripts: [],
  },
};
