import { AuditEvent, AuditSummary } from '@/types/audit';

export const MOCK_AUDIT_EVENTS: AuditEvent[] = [
  {
    id: "evt_O1HX7QV5M8Z2E7JQ91Y5QJH1G2",
    time: "10:21:19",
    relative: "agora",
    date: "16/05/2024",
    title: "Reembolso aprovado",
    category: "REEMBOLSO",
    details: "Reembolso REE-2024-09876 aprovado no valor de R$ 1.259,90",
    meta: "Pedido: ORD-2024-09876 • Cliente: CLI-005782",
    user: "Vinícius Admin",
    role: "Administrador",
    system: "Mercado Pago",
    environment: "Produção",
    ip: "177.12.34.56",
    location: "São Paulo, Brasil",
    level: "Crítico",
    type: "refund",
    entityType: "Reembolso",
    entityId: "REE-2024-09876",
    relatedIds: {
      orderId: "ORD-2024-09876",
      customerId: "CLI-005782"
    },
    metadata: {
      amount: 1259.90,
      currency: "BRL",
      reason: "Solicitado pelo cliente",
      processed_by: "Vinícius Admin",
      risk_level: "low"
    }
  },
  {
    id: "evt_checkout_updated",
    time: "10:20:47",
    relative: "32s atrás",
    date: "16/05/2024",
    title: "Checkout atualizado",
    category: "CHECKOUT",
    details: "Checkout “Checkout Premium v2” atualizado para v2.4.1",
    meta: "Alterado por: Vinícius Admin",
    user: "Vinícius Admin",
    role: "Administrador",
    system: "Basileia Pay",
    environment: "Produção",
    ip: "177.12.34.56",
    location: "São Paulo, Brasil",
    level: "Alteração",
    type: "checkout",
    entityType: "Checkout",
    entityId: "chk_premium_v2",
    metadata: {
      checkout_name: "Checkout Premium v2",
      previous_version: "2.4.0",
      new_version: "2.4.1",
      commit_hash: "8df3e21"
    }
  },
  {
    id: "evt_login_success",
    time: "10:20:12",
    relative: "1m atrás",
    date: "16/05/2024",
    title: "Login realizado",
    category: "ACESSO",
    details: "Usuário realizou login com sucesso",
    meta: "Autenticação: 2FA • Dispositivo: Chrome / macOS",
    user: "Mariana Santos",
    role: "Operador",
    system: "Basileia Pay",
    environment: "Produção",
    ip: "177.98.65.43",
    location: "São Paulo, Brasil",
    level: "Informativo",
    type: "login",
    entityType: "Sessão",
    entityId: "usr_mariana",
    metadata: {
      auth_method: "2FA",
      device: "Chrome / macOS",
      session_duration_limit: "8h"
    }
  },
  {
    id: "evt_api_key_created",
    time: "10:19:58",
    relative: "1m atrás",
    date: "16/05/2024",
    title: "Chave de API criada",
    category: "INTEGRAÇÃO",
    details: "Nova chave de API criada",
    meta: "Escopos: payments.read, refunds.write",
    user: "Rafael Oliveira",
    role: "Dev",
    system: "Basileia Pay",
    environment: "Produção",
    ip: "189.45.67.23",
    location: "Curitiba, Brasil",
    level: "Alteração",
    type: "integration",
    entityType: "API Key",
    entityId: "key_erp_integration",
    metadata: {
      key_name: "Integração ERP",
      scopes: ["payments.read", "refunds.write"],
      expires_at: "2027-05-19T10:19:58Z"
    }
  },
  {
    id: "evt_permissions_updated",
    time: "10:19:31",
    relative: "2m atrás",
    date: "16/05/2024",
    title: "Permissão alterada",
    category: "USUÁRIO",
    details: "Permissão de usuário atualizada",
    meta: "Alvo: Mariana Santos",
    user: "Vinícius Admin",
    role: "Administrador",
    system: "Basileia Pay",
    environment: "Produção",
    ip: "177.12.34.56",
    location: "São Paulo, Brasil",
    level: "Alteração",
    type: "user",
    entityType: "Usuário",
    entityId: "usr_mariana",
    metadata: {
      target_user: "Mariana Santos",
      previous_role: "Suporte",
      new_role: "Operador"
    }
  },
  {
    id: "evt_payment_captured",
    time: "10:18:44",
    relative: "3m atrás",
    date: "16/05/2024",
    title: "Pagamento capturado",
    category: "PAGAMENTO",
    details: "Pagamento capturado com sucesso",
    meta: "Valor: R$ 359,90 • Pix",
    user: "Sistema",
    role: "Webhook",
    system: "Mercado Pago",
    environment: "Produção",
    ip: "34.210.12.44",
    location: "São Paulo, Brasil",
    level: "Informativo",
    type: "payment",
    entityType: "Pagamento",
    entityId: "pay_8f3a2d7e9b1c",
    metadata: {
      gateway: "Mercado Pago",
      amount: 359.90,
      currency: "BRL",
      payment_method: "pix"
    }
  },
  {
    id: "evt_access_denied",
    time: "10:18:02",
    relative: "3m atrás",
    date: "16/05/2024",
    title: "Tentativa de acesso negada",
    category: "SEGURANÇA",
    details: "Tentativa de acesso negada por IP não autorizado",
    meta: "Política: block_foreign_ips",
    user: "Sistema",
    role: "Segurança",
    system: "Basileia Pay",
    environment: "Produção",
    ip: "201.33.44.55",
    location: "Recife, Brasil",
    level: "Crítico",
    type: "security",
    entityType: "Sessão",
    entityId: null,
    metadata: {
      blocked_ip: "201.33.44.55",
      policy: "block_foreign_ips",
      user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
    }
  },
  {
    id: "evt_webhook_delivered",
    time: "10:17:33",
    relative: "4m atrás",
    date: "16/05/2024",
    title: "Webhook entregue",
    category: "WEBHOOK",
    details: "Evento payment.succeeded entregue com sucesso",
    meta: "Endpoint: Mercado Pago - Produção",
    user: "Sistema",
    role: "Webhook",
    system: "Mercado Pago",
    environment: "Produção",
    ip: "54.210.33.21",
    location: "São Paulo, Brasil",
    level: "Informativo",
    type: "webhook",
    entityType: "Webhook",
    entityId: "wh_dlv_01JTK8",
    metadata: {
      endpoint: "Mercado Pago - Produção",
      status_code: 200,
      payload_type: "payment.succeeded"
    }
  },
  {
    id: "evt_subscription_canceled",
    time: "10:17:12",
    relative: "4m atrás",
    date: "16/05/2024",
    title: "Assinatura cancelada",
    category: "ASSINATURA",
    details: "Assinatura cancelada pelo usuário",
    meta: "ID da assinatura: ASS-2024-07345",
    user: "Mariana Santos",
    role: "Operador",
    system: "Basileia Pay",
    environment: "Produção",
    ip: "177.98.65.43",
    location: "São Paulo, Brasil",
    level: "Alteração",
    type: "subscription",
    entityType: "Assinatura",
    entityId: "ASS-2024-07345",
    metadata: {
      subscription_id: "ASS-2024-07345",
      reason: "Solicitado pelo cliente",
      churn_type: "voluntary"
    }
  },
  {
    id: "evt_config_changed",
    time: "10:16:48",
    relative: "5m atrás",
    date: "16/05/2024",
    title: "Configuração alterada",
    category: "CONFIGURAÇÃO",
    details: "Configuração de antifraude atualizada",
    meta: "Chave: antifraud_rules",
    user: "Vinícius Admin",
    role: "Administrador",
    system: "Basileia Pay",
    environment: "Produção",
    ip: "177.12.34.56",
    location: "São Paulo, Brasil",
    level: "Alteração",
    type: "config",
    entityType: "Configuração",
    entityId: "cfg_antifraud_rules",
    metadata: {
      config_key: "antifraud_rules",
      previous_action: "review",
      new_action: "reject"
    }
  }
];

export const MOCK_SUMMARY: AuditSummary = {
  totalEvents: 24812,
  activeUsers: 32,
  impactedEntities: 158,
  systemsInvolved: 8,
  criticalActions: 71,
  lastEventAt: "2026-05-19T10:21:19Z"
};
