[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:php-fpm]
command=php-fpm -F
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/php-fpm.log
stderr_logfile=/var/log/supervisor/php-fpm_err.log
environment=APP_ENV="production"

[program:nginx]
command=nginx -g "daemon off; pid /run/nginx/nginx.pid;"
user=root
autostart=true
autorestart=true
startsecs=3
stdout_logfile=/var/log/supervisor/nginx.log
stderr_logfile=/var/log/supervisor/nginx_err.log

[program:horizon]
command=php /var/www/html/artisan queue:work --sleep=3 --tries=3 --max-time=3600
user=www-data
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/queue.log
stderr_logfile=/var/log/supervisor/queue_err.log
numprocs=2
process_name=%(program_name)s_%(process_num)02d
